version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: argus_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: argus
      POSTGRES_PASSWORD: argus_dev_password
      POSTGRES_DB: argus
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U argus"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: